dataSource:
  - addr: 3.20.122.137
    port: 3306
    username: root
    password: "!devpass123456"
    idle_conn: 10
    max_conn: 20
    max_idle_time: 20
    max_life_time: 20
    charset: utf8mb4
    db_name: metaspace
    name: metaspace
    type: mysql
    slow_sql: 100 #ms
redis:
  - host: 3.20.122.137:6379
    password: "!devpass123456"
    db: 1
    name: metaspace
jwt:
  secret: 12345678
grpc:
  host: "127.0.0.1"
  port: "10011"
contract:
  eth_client: "https://rinkeby.infura.io/v3/059609bf2c8e433d8ad4a895a98278ed"
  address: "0xc10641031430cF29579f829952b118f1d873bbc2"